[tools]
age = "latest"
ansible = "latest"
argocd = "latest"
bat = "latest"
"cargo:comtrya" = "latest"
"cargo:macchina" = "latest"
chezmoi = "latest"
cmake = "latest"
dagger = "latest"
dapr = "latest"
direnv = "latest"
dotnet = "latest"
eza = "latest"
fd = "latest"
flux2 = "latest"
github-cli = "latest"
go = "latest"
helm = "latest"
java = "openjdk-23"
jbang = "latest"
jq = "latest"
k0sctl = "latest"
k9s = "latest"
kind = "latest"
kn = "latest"
krew = "latest"
kubebuilder = "latest"
kubectl = "latest"
kubectx = "latest"
lazygit = "latest"
maven = "latest"
neovim = "latest"
nodejs = "latest"
"npm:next" = "latest"
ollama = "latest"
opentofu = "latest"
operator-sdk = "latest"
quarkus = "latest"
ripgrep = "latest"
rust = "latest"
sops = "latest"
starship = "latest"
talosctl = "latest"
task = "latest"
terraform = "latest"
usage = "latest"
uv = "latest"
watchexec = "latest"
yq = "latest"
zoxide = "latest"

[tasks.flux_bootstrap]
run = "flux bootstrap github --owner=michaelwillingham --repository=flux-config --branch=main --path=clusters/willingham-cloud-talos --personal --ssh-key ~/.ssh/id_ed25519"
