[tools]
age = "latest"
argocd = "latest"
bat = "latest"
bun = "latest"
cilium-cli = "latest"
clusterctl = "latest"
cmctl = "latest"
cmake = "latest"
coder = "latest"
ctlptl = "latest"
dotnet = "latest"
"dotnet:nbgv" = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
go = "latest"
helm = "latest"
imagemagick = "latest"
java = "latest"
jq = "latest"
k9s = "latest"
kind = "latest"
kn = "latest"
kubebuilder = "latest"
kubectl = "latest"
kubectx = "latest"
kubelogin = "latest"
kubens = "latest"
mas = "latest"
minikube = "latest"
neovim = "latest"
node = "latest"
omnictl = "latest"
ripgrep = "latest"
ruff = "latest"
sops = "latest"
talosctl = "latest"
temporal = "latest"
tilt = "latest"
tmux = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
k0sctl = "latest"
bazel = "latest"
task = "latest"
infisical = { version = "latest", asset_pattern = "cli_{{ version }}_{{ os(macos='darwin') }}_{{ arch(x64='amd64') }}.tar.gz" }
"aqua:tailscale/tailscale" = "latest"
crossplane = "latest"
rust = "latest"
jbang = "latest"
openbao = "latest"
grok = { version = "latest", bin = "grok", platforms = { windows-arm64 = { bin = "grok.exe", url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-windows-aarch64.exe" }, windows-x64 = { bin = "grok.exe", url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-windows-x86_64.exe" } }, url = 'https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-{{ os() }}-{{ arch(x64="x86_64", arm64="aarch64") }}', version_list_url = "https://x.ai/cli/stable" }

[settings]
experimental = true
npm.package_manager = "bun"

[settings.github]
use_git_credentials = true
