[tools]
age = "latest"
argocd = "latest"
bat = "latest"
chezmoi = "latest"
cmake = "latest"
dagger = "latest"
dapr = "latest"
direnv = "latest"
dotnet = "latest"
eza = "latest"
fd = "latest"
flux2 = "latest"
gcloud = "latest"
github-cli = "latest"
go = "latest"
helm = "latest"
java = "openjdk-23"
jbang = "latest"
jq = "latest"
k9s = "latest"
kind = "latest"
kn = "latest"
krew = "latest"
kubectl = "latest"
kubectx = "latest"
lazygit = "latest"
make = "latest"
maven = "latest"
neovim = "latest"
nodejs = "latest"
ollama = "latest"
opentofu = "latest"
operator-sdk = "latest"
quarkus = "latest"
ripgrep = "latest"
rust = "latest"
sops = "latest"
starship = "latest"
talosctl = "latest"
task = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
